#!/usr/bin/env python3
import ipdb
from os import listdir
from os.path import isfile, join
import re
import numpy as np
from matplotlib import pyplot as plt
from scipy.fft import fft, ifft, fftfreq

logdir="/tmp/tcpserver_data" #  .../2022-03-22--04:14AM

files = [ fn for fn in listdir(logdir) if re.match(r'^\d\d\d\d-\d\d', fn) ]
files.sort()
logfn = join(logdir, files[-1])
print("Using logfile:", logfn)

def proclog(fn=None):
	vals = []
	f = open(logfn)
	for line in f:
		us, val = line.strip().split(" ")
		val = float(val)
		if val != 2 and val != 1024 and val != 0:
			# print(us, "val:", val)
			vals.append(val)
	return np.array(vals)

def prepdata(vals):
	N = 500
	# sample spacing
	T = 1.0 / 1000.0
	x = np.linspace(0.0, N*T, N, endpoint=False)
	yf = fft(vals)
	xf = fftfreq(N, T)[:N//2]
	print(yf)
	plt.plot(xf, 2.0/N * np.abs(yf[0:N//2]))
	plt.grid()
	plt.show()
	#histo = np.histogram(vals, bins=50)
	#plt.hist(vals)
	#plt.show()

def main():
	vals = proclog(logfn)
	prepdata(vals)

main()


